var gameConfig = {
	game:{
		gameName:"Viz",
		gameType:"slot",
		channel:"I",
		gameWidth:1024,
		gameHeight:600,
		antialias:true,
		transparent:false,
		forceCanvas:true,
		resolution:1
	},
	connection:{
		//§"connectionURL": "http://localhost:8888/xml/",
		connectionURL: "http://192.168.1.22:8888/xml/bal/",
		testresponse: ["init.xml","spin1.xml"],
		freeBets: "Yes",
        freePlay: true,
        isGuest: "No",
        cookie: "",
        connectionType: "OpenBetReelConnection",
        gameClass: "Slot",
        gameName: "Viz",
        freeGameName: "FreeViz",
        channel: "I",
        connectionTimeOut: 30000
	},
	assets:{
		images:{
			files:[
				{name:"gamebg", url:"assets/images/x2/gamebg.jpg"},
				{name:"reelframe", url:"assets/images/x2/reelframe.png"},
				{name:"reellogo", url:"assets/images/x2/reellogo.png"},
				{name:"reelSymbols", url:"assets/images/x2/Reel-Symbols.png"},
				{name:"reelSymbols2", url:"assets/images/x2/Reel-Symbols2.png"},
				{name:"reelSymbols4", url:"assets/images/x2/Reel-Symbols4.png"},
				{name:"wildanim1", url:"assets/images/x2/wildanim1.png"},
				{name:"wildanim2", url:"assets/images/x2/wildanim2.png"},

				{name:"spinBtn", url:"assets/ui/spin.png"},
				{name:"autoPlayBtn", url:"assets/ui/Auto.png"},
				{name:"helpBtn", url:"assets/ui/info.png"},
				{name:"settingsBtn", url:"assets/ui/settings.png"},
				{name:"stakeBtn", url:"assets/ui/stake.png"},
				{name:"stakeValue", url:"assets/ui/stakeValue.png"},
				{name:"applyBtn", url:"assets/ui/apply.png"},
				{name:"closeBtn", url:"assets/ui/close.png"},
				{name:"autoTextBox", url:"assets/ui/autoTextBox.png"},
				{name:"autoValue", url:"assets/ui/AutoValue.png"}

			],
			textureMaps:[
				{
					imageName:"reelSymbols",
					imagePositions:[
						{
							id:"Book",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"Coin",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Cauldron",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols4",
					imagePositions:[
						{
							id:"GoldVial",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"BlueVial",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"PinkVial",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols2",
					imagePositions:[
						{
							id:"CharacterHead",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"WildOrb1",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Ace",
							x:0,
							y:232,
							width:120,
							height:116
						},
						{
							id:"King",
							x:0,
							y:348,
							width:120,
							height:116
						},
						{
							id:"Queen",
							x:0,
							y:464,
							width:120,
							height:116
						},
						{
							id:"Jack",
							x:0,
							y:580,
							width:120,
							height:116
						},
						{
							id:"Ten",
							x:0,
							y:696,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"applyBtn",
					imagePositions:[
						{
							id:"applyBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"applyBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"closeBtn",
					imagePositions:[
						{
							id:"closeBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"closeBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"stakeValue",
					imagePositions:[
						{
							id:"stakeValueDisabled",
							x:0,
							y:0,
							width:182,
							height:60
						},
						{
							id:"stakeValueUp",
							x:182,
							y:0,
							width:182,
							height:60
						},
						{
							id:"stakeValueDown",
							x:364,
							y:0,
							width:182,
							height:60
						}
					]
				},
				{
					imageName:"autoValue",
					imagePositions:[
						{
							id:"autoValueUp",
							x:0,
							y:0,
							width:119,
							height:40
						},
						{
							id:"autoValueDown",
							x:119,
							y:0,
							width:119,
							height:40
						},
						{
							id:"autoValueDisabled",
							x:238,
							y:0,
							width:119,
							height:40
						}
					]
				},
				{
					imageName:"settingsBtn",
					imagePositions:[
						{
							id:"settingsBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"settingsBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						},
						{
							id:"settingsBtnDown",
							x:116,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"stakeBtn",
					imagePositions:[
						{
							id:"stakeBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"stakeBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						},
						{
							id:"stakeBtnDown",
							x:116,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"helpBtn",
					imagePositions:[
						{
							id:"helpBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"helpBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						},
						{
							id:"helpBtnDown",
							x:116,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"autoPlayBtn",
					imagePositions:[
						{
							id:"autoPlayBtnUp",
							x:0,
							y:0,
							width:58,
							height:58
						},
						{
							id:"autoPlayBtnDisabled",
							x:58,
							y:0,
							width:58,
							height:58
						},
						{
							id:"autoPlayBtnDown",
							x:116,
							y:0,
							width:58,
							height:58
						}
					]
				},
				{
					imageName:"spinBtn",
					imagePositions:[
						{
							id:"spinBtnUp",
							x:0,
							y:0,
							width:131,
							height:131
						},
						{
							id:"spinBtnDisabled",
							x:131,
							y:0,
							width:131,
							height:131
						},
						{
							id:"spinBtnDown",
							x:262,
							y:0,
							width:131,
							height:131
						}
					]
				}
			],
			textureMapsx2:[
				{
					imageName:"reelSymbols",
					imagePositions:[
						{
							id:"Book",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"Coin",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Cauldron",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols4",
					imagePositions:[
						{
							id:"GoldVial",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"BlueVial",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"PinkVial",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols2",
					imagePositions:[
						{
							id:"CharacterHead",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"WildOrb1",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Ace",
							x:0,
							y:232,
							width:120,
							height:116
						},
						{
							id:"King",
							x:0,
							y:348,
							width:120,
							height:116
						},
						{
							id:"Queen",
							x:0,
							y:464,
							width:120,
							height:116
						},
						{
							id:"Jack",
							x:0,
							y:580,
							width:120,
							height:116
						},
						{
							id:"Ten",
							x:0,
							y:696,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"applyBtn",
					imagePositions:[
						{
							id:"applyBtnUp",
							x:0,
							y:0,
							width:117,
							height:116
						},
						{
							id:"applyBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:116
						}
					]
				},
				{
					imageName:"closeBtn",
					imagePositions:[
						{
							id:"closeBtnUp",
							x:0,
							y:0,
							width:117,
							height:116
						},
						{
							id:"closeBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:116
						}
					]
				},
				{
					imageName:"stakeValue",
					imagePositions:[
						{
							id:"stakeValueDisabled",
							x:0,
							y:0,
							width:361,
							height:120
						},
						{
							id:"stakeValueUp",
							x:361,
							y:0,
							width:361,
							height:120
						},
						{
							id:"stakeValueDown",
							x:722,
							y:0,
							width:361,
							height:120
						}
					]
				},
				{
					imageName:"autoValue",
					imagePositions:[
						{
							id:"autoValueUp",
							x:0,
							y:0,
							width:239,
							height:80
						},
						{
							id:"autoValueDown",
							x:239,
							y:0,
							width:239,
							height:80
						},
						{
							id:"autoValueDisabled",
							x:478,
							y:0,
							width:239,
							height:80
						}
					]
				},
				{
					imageName:"settingsBtn",
					imagePositions:[
						{
							id:"settingsBtnUp",
							x:0,
							y:0,
							width:117,
							height:117
						},
						{
							id:"settingsBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:117
						},
						{
							id:"settingsBtnDown",
							x:234,
							y:0,
							width:117,
							height:117
						}
					]
				},
				{
					imageName:"stakeBtn",
					imagePositions:[
						{
							id:"stakeBtnUp",
							x:0,
							y:0,
							width:117,
							height:117
						},
						{
							id:"stakeBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:117
						},
						{
							id:"stakeBtnDown",
							x:234,
							y:0,
							width:117,
							height:117
						}
					]
				},
				{
					imageName:"helpBtn",
					imagePositions:[
						{
							id:"helpBtnUp",
							x:0,
							y:0,
							width:117,
							height:117
						},
						{
							id:"helpBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:117
						},
						{
							id:"helpBtnDown",
							x:234,
							y:0,
							width:117,
							height:117
						}
					]
				},
				{
					imageName:"autoPlayBtn",
					imagePositions:[
						{
							id:"autoPlayBtnUp",
							x:0,
							y:0,
							width:117,
							height:117
						},
						{
							id:"autoPlayBtnDisabled",
							x:117,
							y:0,
							width:117,
							height:117
						},
						{
							id:"autoPlayBtnDown",
							x:234,
							y:0,
							width:117,
							height:117
						}
					]
				},
				{
					imageName:"spinBtn",
					imagePositions:[
						{
							id:"spinBtnUp",
							x:0,
							y:0,
							width:262,
							height:262
						},
						{
							id:"spinBtnDisabled",
							x:262,
							y:0,
							width:262,
							height:262
						},
						{
							id:"spinBtnDown",
							x:524,
							y:0,
							width:262,
							height:262
						}
					]
				}
			]
		},
		sounds:{
			files:[
				{name:"btnClickSound", url:"assets/sounds/bottomBarButton.m4a"}
			],
		},
		fonts:{
			files:[
				{name:"MyriadProRegular", url:"assets/fonts/MyriadProRegular.ttf"}
			],
			styles:{
				families: ['MyriadProRegular', 'Arial'],
				fontFamily:"MyriadProRegular",
				fonSize:24,
				fill:"#ffffff"
			}
		}
	},
	background:{
		type:"Sprite",
		imageName:"gamebg",
		fullScreen:true
	},
	ui:{
		children:[
			{
				type:"GameUI",
				id:"gameUI",
				x:0,
				y:0,
				buttonPanelPos:"right",
				children:[
					{
						type:"Container",
						id:"buttonPanelUI",
						x:0,
						y:0,
						children:[
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"spinBtn",
							
								x:0,
								y:64,
								state:{
									up:{
										imageName:"spinBtnUp"
									},
									disabled:{
										imageName:"spinBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"helpBtn",
							
								x:73.5,
								y:0,
								state:{
									up:{
										imageName:"helpBtnUp"
									},
									disabled:{
										imageName:"helpBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"autoPlayBtn",
							
								x:0,
								y:0,
								state:{
									up:{
										imageName:"autoPlayBtnUp"
									},
									disabled:{
										imageName:"autoPlayBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"stakeBtn",
							
								x:0,
								y:200,
								state:{
									up:{
										imageName:"stakeBtnUp"
									},
									disabled:{
										imageName:"stakeBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"settingsBtn",
							
								x:73.5,
								y:200,
								state:{
									up:{
										imageName:"settingsBtnUp"
									},
									disabled:{
										imageName:"settingsBtnDisabled"
									}
								}
							}
						]
					},
					{
						type:"BottomBarUI",
						id:"buttomBarUI",
						position:"bottom"
					},
					{
						type:"Container",
						id:"autoplayPanel",
						x:0,
						y:0,
						visible:false,
						children:[
							{
								type:"Sprite",
								x:20,
								y:120,
							
								imageName:"autoTextBox"
							},
							{
								type:"Text",
								text:"Numper of plays:",
								align:"left",
								x:40,
								y:128,
								style:{
									colour:"#f7ba0c",
									fontSize:15,
									fontFamily:"MyriadProRegular"
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"closeBtn",
							
								x:600,
								y:100,
								state:{
									up:{
										imageName:"closeBtnUp"
									},
									disabled:{
										imageName:"closeBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"applyBtn",
							
								x:600,
								y:450,
								state:{
									up:{
										imageName:"applyBtnUp"
									},
									disabled:{
										imageName:"applyBtnDisabled"
									}
								}
							}
						]
					},
					{
						type:"StakePanel",
						id:"stakePanel",
						x:0,
						y:0,
						visible:false,
						btnWidth:190,
						btnHeight:70,
						startX:600,
						startY:130,
						optionValue:{
							x:0,
							y:0,
							value:"1",
							textColour:"#f7ba0c",
							text:{
								x:90,
								y:18,
								text:"£1.00",
								style:{
									colour:"#f7ba0c",
									fontSize:25,
									fontFamily:"MyriadProRegular"
								}
								
							},
							button:{
								action:"Button",
								sound:"btnClickSound",
								id:"closeBtn",
							
								x:0,
								y:0,
								state:{
									up:{
										imageName:"stakeValueUp"
									},
									disabled:{
										imageName:"stakeValueDisabled"
									}
								}
							}					
						},
						children:[
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"closeBtn",
							
								x:600,
								y:100,
								state:{
									up:{
										imageName:"closeBtnUp"
									},
									disabled:{
										imageName:"closeBtnDisabled"
									}
								}
							},
							{
								type:"Button",
								action:"Button",
								sound:"btnClickSound",
								id:"applyBtn",
							
								x:600,
								y:450,
								state:{
									up:{
										imageName:"applyBtnUp"
									},
									disabled:{
										imageName:"applyBtnDisabled"
									}
								}
							}
						]
					}
				]
			}
		]		
	},
	screens:{
		children:[
			{
				id:"reelScreen",
				type:"ReelScreen",
				children:[
					{
						type:"Graphic",
						x:0,
						y:0,
						lineColour:"0x000000",
						rect:{
							x:0,
							y:0,
							width:1024,
							height:600
						}
					},
					{
						type:"ReelContainer",
						id:"reelContainer",
						x:190,
						y:170,
						children:[
							{
								type:"Container",
								id:"reelsContainer",
								x:0,
								y:0,
								reels:{
									reelWidth: 124.5,
									numberOfReels:5,
									symbolWidth: 122,
									symbolHeight: 116,
									symbolsInView:3,
									spinSpeed:29,
									symbolXSpacer:4,
									symbolYSpacer:0,
									reelBlur:10,
									reelDelay:10,
									reelStopDelay:10,
									rampUpSpeed:5,
									rampUpDistance:50,
									bounceDistance:30,
									bounceUpSpeed:5,
									symbolWinAlpha:0.3,
									slotTextures:[
										"GoldVial",
										"BlueVial",
										"PinkVial",
										"Coin",
										"CharacterHead",
										"Cauldron",
										"Book",
										"Ace",
										"King",
										"Queen",
										"Jack",
										"Ten",
										"WildOrb1",
										"WildOrb1",
										"WildOrb1"
									]
								},
								mask:{
									id:"reelMask",
									tgt:"reelsContainer",
									type:"Graphic",
									x:0,
									y:0,
									colour:"0xff00000",
									rect:{
										x:0,
										y:0,
										width:635,
										height:348
									}
								}
							}
						]
					},
					{
						type:"Sprite",
						x:121,
						y:10,
						imageName:"reelframe"
					},

					{
						type:"Sprite",
						imageName:"reellogo",
						x:252,
						y:32
					},
					{
						type:"WinlineContainer",
						id:"winlineContainer",
						x:190,
						y:170,
						width:640,
						height:348,
						symbolSize:{width:126.5, height:116},
						winlinePatterns:"",
						winlineSize:6,
						winlines:[
							"0xff0000",
							"0x0070bb",
							"0x002585",
							"0xffcfb9",
							"0xff62a8",
							"0xff8b00",
							"0xff137c",
							"0x00ff00",
							"0xfbd920",
							"0xff2b00",
							"0x60ffff",
							"0xffff00",
							"0x29abe1",
							"0xacff3e",
							"0x29abe1",
							"0xacacac",
							"0x00a060",
							"0xdb0000",
							"0x5258ff",
							"0x00d100",
							"0xd9df20"
						]
					},
					
					
					
					
					
				]
			}
			
		]
	}

}