var gameConfig = {
	game:{
		gameName:"Plum Royale",
		gameType:"slot",
		channel:"I",
		gameWidth:1024,
		gameHeight:576,
		antialias:true,
		logLevel:5,
		transparent:false,
		forceCanvas:true,
		resolution:1,
		topBar:{
			type:'GCMTopBar',
			path:'../../gcm/js/gcmBridge.js'
		}
	},
	connection:{
		connectionURL: "https://fog-integration-casino-games-8.casino.openbet.com//cc_head/fog/Servlet",
		freeBets: "Yes",
		freePlay: true,
		isGuest: "No",
        cookie: "",  //aTXR2Ebm0cttL7VcGkgLTG+KvUXbAWPho4Yf4szdcDPmIIbOK9faIUENP+t7iNr00L7/FHo= //hungryBear250
        connectionType: "OpenBetReelConnection",
        gameClass: "Slot",
        gameName: "PlumRoyale20HB",
        freeGameName: "FreePlumRoyale20HB",
        channel: "I",
        connectionTimeOut: 30000
    },
    assets:{
    	images:{
    		files:[
    		{name:"gamebg", url:"assets/images/gameBackground.png"},
    		{name:"reelSymbols", url:"assets/images/symbols.png"},
    		{name:"loadingBG", url:"assets/images/loading.png"},
    		{name:"rightWinLines", url:"assets/images/rightWinLines.png"},
    		{name:"leftWinLines", url:"assets/images/leftWinLines.png"}
    		],
    		textureMaps:[
    		{
    			imageName:"reelSymbols",
    			imagePositions:[
    			{
    				id:"Plum",
    				x:0,
    				y:0,
    				width:146,
    				height:146
    			},
    			{
    				id:"Cheese",
    				x:0,
    				y:146,
    				width:146,
    				height:146
    			},
    			{
    				id:"Bar",
    				x:0,
    				y:292,
    				width:146,
    				height:146
    			},
    			{
    				id:"Red7",
    				x:0,
    				y:438,
    				width:146,
    				height:146
    			},
    			{
    				id:"Blue7",
    				x:0,
    				y:584,
    				width:146,
    				height:146
    			},
    			{
    				id:"Bell",
    				x:0,
    				y:730,
    				width:146,
    				height:146
    			},
    			{
    				id:"Melon",
    				x:0,
    				y:876,
    				width:146,
    				height:146
    			},
    			{
    				id:"Lemon",
    				x:0,
    				y:1022,
    				width:146,
    				height:146
    			},
    			{
    				id:"Cherry",
    				x:0,
    				y:1168,
    				width:146,
    				height:146
    			},
    			{
    				id:"Wild",
    				x:0,
    				y:1314,
    				width:146,
    				height:146
    			}
    			]
    		},
    		{
    			imageName:"leftWinLines",
    			imagePositions:[
    			{
    				id:"Lwl1",
    				x:0,
    				y:0,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl2",
    				x:0,
    				y:32,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl3",
    				x:0,
    				y:64,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl4",
    				x:0,
    				y:96,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl5",
    				x:0,
    				y:128,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl6",
    				x:0,
    				y:160,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl7",
    				x:0,
    				y:192,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl8",
    				x:0,
    				y:224,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl9",
    				x:0,
    				y:256,
    				width:84,
    				height:32
    			},
    			{
    				id:"Lwl10",
    				x:0,
    				y:288,
    				width:84,
    				height:32
    			}
    			]
    		},	
    		{
    			imageName:"rightWinLines",
    			imagePositions:[
    			{
    				id:"Rwl1",
    				x:0,
    				y:0,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl2",
    				x:0,
    				y:32,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl3",
    				x:0,
    				y:64,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl4",
    				x:0,
    				y:96,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl5",
    				x:0,
    				y:128,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl6",
    				x:0,
    				y:160,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl7",
    				x:0,
    				y:192,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl8",
    				x:0,
    				y:224,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl9",
    				x:0,
    				y:256,
    				width:84,
    				height:32
    			},
    			{
    				id:"Rwl10",
    				x:0,
    				y:288,
    				width:84,
    				height:32
    			}
    			]
    		},	
    		]
    	},
    	sounds:{
    		files:[
    		{name:"btnClickSound1", url:"assets/sounds/bottomBarButton.m4a"}
    		],
    	},
    	fonts:{
    		files:[
    		{name:"MyriadProRegular", url:"assets/fonts/MyriadProRegular.ttf"}
    		],
    		styles:{
    			families: ['MyriadProRegular', 'Arial'],
    			fontFamily:"MyriadProRegular",
    			fonSize:24,
    			fill:"#ffffff"
    		}
    	}
    },
    background:{
    	type:"Sprite",
    	imageName:"gamebg",
    	fullScreen:true
    },
    screens:{
    	startScreen:"welcomeScreen",
    	welcomeTransitionFade:true,
    	children:[
    	{
    		id:"welcomeScreen",
    		type:"Screen",
    		children:[
    		{
    			type:"Graphic",
    			x:0,
    			y:0,
    			colour:"0x000000",
    			rect:{
    				x:0,
    				y:0,
    				width:1024,
    				height:600
    			}
    		},
    		{
    			type:"Sprite",
    			imageName:"loadingBG",
    			x:0,
    			y:0
    		},
    		{
    			"type":"Button",
    			"action":"Button",
    			"sound":"btnClickSound",
    			"id":"startGameBtn",
    			"x":466,
    			"y":450,
    			"state":{
    				up:{
    					imageName:"startGameBtnUp"
    				},
    				disabled:{
    					imageName:"startGameBtnDisabled"
    				},
    				down:{
    					imageName:"startGameBtnDown"
    				}
    			}
    		},
    		{
    			type:"Graphic",
    			x:0,
    			y:0,
    			lineSize:2,
    			lineColour:"0xffc600",
    			rect:{
    				x:1,
    				y:1,
    				width:1022,
    				height:574
    			}
    		}
    		]
    	},
    	{
    		id:"reelScreen",
    		//type:"ReelScreen",
            type:"BarKingReelScreen",
            winlineDelay: 60,
    		children:[
    		{
    			type:"Graphic",
    			x:0,
    			y:0,
    			lineColour:"0x000000",
    			rect:{
    				x:0,
    				y:0,
    				width:1024,
    				height:576
    			}
    		},
    		{
    			type:"ReelContainer",
    			id:"reelContainer",
    			x:144,
    			y:50,
    			children:[
    			{
    				type:"Container",
    				id:"reelsContainer",
    				x:0,
    				y:0,
    				reels:{
    					reelWidth: 146,
    					numberOfReels:5,
    					symbolWidth: 146,
    					symbolHeight: 146,
    					symbolsInView:3,
    					spinSpeed:29,
    					symbolXSpacer:0,
    					symbolYSpacer:1,
    					reelBlur:10,
    					reelDelay:10,
    					reelStopDelay:10,
    					rampUpSpeed:5,
    					rampUpDistance:50,
    					bounceDistance:30,
    					bounceUpSpeed:5,
    					symbolWinAlpha:0.3,
    					slotTextures:[
    					"Cherry",
    					"Lemon",
    					"Melon",
    					"Bar",
    					"Bell",
    					"Blue7",
    					"Red7",
    					"Plum",
    					"Cheese",
    					"Wild"
    					]
    				},
    				mask:{
    					id:"reelMask",
    					tgt:"reelsContainer",
    					type:"Graphic",
    					x:0,
    					y:0,
    					colour:"0xff00000",
    					rect:{
    						x:0,
    						y:0,
    						width:770,
    						height:440
    					}
    				}
    			}
    			]
    		},

    		{
    			type:"WinlineContainer",
    			id:"winlineContainer",
    			x:144,
    			y:50,
    			width:640,
    			height:400,
    			symbolSize:{width:146, height:146},
    			winlinePatterns:"",
    			winlineSize:6,
    			winlines:[
    			"0xff0000",
    			"0x0070bb",
    			"0x002585",
    			"0xffcfb9",
    			"0xff62a8",
    			"0xff8b00",
    			"0xff137c",
    			"0x00ff00",
    			"0xfbd920",
    			"0xff2b00",
    			"0x60ffff",
    			"0xffff00",
    			"0x29abe1",
    			"0xacff3e",
    			"0x29abe1",
    			"0xacacac",
    			"0x00a060",
    			"0xdb0000",
    			"0x5258ff",
    			"0x00d100",
    			"0xd9df20"
    			]
    		},	
			{
				type:"Container",
				id:"leftWinLinesPanel",
				x:55,
				y:50,
				children:[
					{
						type:"Sprite",
						imageName:"Lwl1",
						x:0,
						y:0
					},
					{
						type:"Sprite",
						imageName:"Lwl2",
						x:0,
						y:44
					},
					{
						type:"Sprite",
						imageName:"Lwl3",
						x:0,
						y:88
					},
					{
						type:"Sprite",
						imageName:"Lwl4",
						x:0,
						y:132
					},
					{
						type:"Sprite",
						imageName:"Lwl5",
						x:0,
						y:176
					},
					{
						type:"Sprite",
						imageName:"Lwl6",
						x:0,
						y:220
					},
					{
						type:"Sprite",
						imageName:"Lwl7",
						x:0,
						y:264
					},
					{
						type:"Sprite",
						imageName:"Lwl8",
						x:0,
						y:308
					},
					{
						type:"Sprite",
						imageName:"Lwl9",
						x:0,
						y:352
					},
					{
						type:"Sprite",
						imageName:"Lwl10",
						x:0,
						y:396
					}
				]
			},
			{
				type:"Container",
				id:"RightWinLinesPanel",
				x:880,
				y:50,
				children:[
					{
						type:"Sprite",
						imageName:"Rwl1",
						x:0,
						y:0
					},
					{
						type:"Sprite",
						imageName:"Rwl2",
						x:0,
						y:44
					},
					{
						type:"Sprite",
						imageName:"Rwl3",
						x:0,
						y:88
					},
					{
						type:"Sprite",
						imageName:"Rwl4",
						x:0,
						y:132
					},
					{
						type:"Sprite",
						imageName:"Rwl5",
						x:0,
						y:176
					},
					{
						type:"Sprite",
						imageName:"Rwl6",
						x:0,
						y:220
					},
					{
						type:"Sprite",
						imageName:"Rwl7",
						x:0,
						y:264
					},
					{
						type:"Sprite",
						imageName:"Rwl8",
						x:0,
						y:308
					},
					{
						type:"Sprite",
						imageName:"Rwl9",
						x:0,
						y:352
					},
					{
						type:"Sprite",
						imageName:"Rwl10",
						x:0,
						y:396
					}
				]
			},		
    		]
    	}
    	]
    },
    ui:{
    	buttonPanelPos:"right",
    	uiType:"default",
    	helpPages:[]
    }
}