var gameConfig = {
	game:{
		gameName:"Plum Royale",
		gameType:"slot",
		channel:"I",
		gameWidth:1024,
		gameHeight:600,
		antialias:true,
		logLevel:5,
		transparent:false,
		forceCanvas:true,
		resolution:1,
		topBar:{
			type:'GCMTopBar',
			path:'../../gcm/js/gcmBridge.js'
		}
	},
	connection:{
	
		connectionURL: "https://fog-integration-casino-games-8.casino.openbet.com//cc_head/fog/Servlet",
		freeBets: "Yes",
        freePlay: true,
        isGuest: "No",
        cookie: "",
        connectionType: "OpenBetReelConnection",
        gameClass: "Slot",
        gameName: "PlumRoyale20",
        freeGameName: "FreePlumRoyale20",
        channel: "I",
        connectionTimeOut: 30000
	},
	assets:{
		images:{
			files:[
				{name:"gamebg", url:"assets/images/gamebg.jpg"},
				{name:"reelframe", url:"assets/images/reelframe.png"},
				{name:"reellogo", url:"assets/images/reellogo.png"},
				{name:"reelSymbols", url:"assets/images/Reel-Symbols.png"},
				{name:"reelSymbols2", url:"assets/images/Reel-Symbols2.png"},
				{name:"reelSymbols4", url:"assets/images/Reel-Symbols4.png"},
				{name:"wildanim1", url:"assets/images/wildanim1.png"},
				{name:"wildanim2", url:"assets/images/wildanim2.png"}

			],
			textureMaps:[
				{
					imageName:"reelSymbols",
					imagePositions:[
						{
							id:"Book",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"Coin",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Cauldron",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols4",
					imagePositions:[
						{
							id:"GoldVial",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"BlueVial",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"PinkVial",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols2",
					imagePositions:[
						{
							id:"CharacterHead",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"WildOrb1",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Ace",
							x:0,
							y:232,
							width:120,
							height:116
						},
						{
							id:"King",
							x:0,
							y:348,
							width:120,
							height:116
						},
						{
							id:"Queen",
							x:0,
							y:464,
							width:120,
							height:116
						},
						{
							id:"Jack",
							x:0,
							y:580,
							width:120,
							height:116
						},
						{
							id:"Ten",
							x:0,
							y:696,
							width:120,
							height:116
						}
					]
				},
				
			],
			textureMapsx2:[
				{
					imageName:"reelSymbols",
					imagePositions:[
						{
							id:"Book",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"Coin",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Cauldron",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols4",
					imagePositions:[
						{
							id:"GoldVial",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"BlueVial",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"PinkVial",
							x:0,
							y:232,
							width:120,
							height:116
						}
					]
				},
				{
					imageName:"reelSymbols2",
					imagePositions:[
						{
							id:"CharacterHead",
							x:0,
							y:0,
							width:120,
							height:116
						},
						{
							id:"WildOrb1",
							x:0,
							y:116,
							width:120,
							height:116
						},
						{
							id:"Ace",
							x:0,
							y:232,
							width:120,
							height:116
						},
						{
							id:"King",
							x:0,
							y:348,
							width:120,
							height:116
						},
						{
							id:"Queen",
							x:0,
							y:464,
							width:120,
							height:116
						},
						{
							id:"Jack",
							x:0,
							y:580,
							width:120,
							height:116
						},
						{
							id:"Ten",
							x:0,
							y:696,
							width:120,
							height:116
						}
					]
				},
				
			]
		},
		sounds:{
			files:[
				{name:"btnClickSound1", url:"assets/sounds/bottomBarButton.m4a"}
			],
		},
		fonts:{
			files:[
				{name:"MyriadProRegular", url:"assets/fonts/MyriadProRegular.ttf"}
			],
			styles:{
				families: ['MyriadProRegular', 'Arial'],
				fontFamily:"MyriadProRegular",
				fonSize:24,
				fill:"#ffffff"
			}
		}
	},
	background:{
		type:"Sprite",
		imageName:"gamebg",
		fullScreen:true
	},
	ui:{
		buttonPanelPos:"right",
		uiType:"default",
		helpPages:[]
	},
	screens:{
		children:[
			{
				id:"reelScreen",
				type:"ReelScreen",
				children:[
					{
						type:"Graphic",
						x:0,
						y:0,
						lineColour:"0x000000",
						rect:{
							x:0,
							y:0,
							width:1024,
							height:600
						}
					},
					{
						type:"ReelContainer",
						id:"reelContainer",
						x:190,
						y:174,
						children:[
							{
								type:"Container",
								id:"reelsContainer",
								x:0,
								y:0,
								reels:{
									reelWidth: 120,
									numberOfReels:5,
									symbolWidth: 120,
									symbolHeight: 116,
									symbolsInView:3,
									spinSpeed:29,
									symbolXSpacer:4,
									symbolYSpacer:0,
									reelBlur:10,
									reelDelay:10,
									reelStopDelay:10,
									rampUpSpeed:5,
									rampUpDistance:50,
									bounceDistance:30,
									bounceUpSpeed:5,
									symbolWinAlpha:0.3,
									slotTextures:[
										"GoldVial",
										"BlueVial",
										"PinkVial",
										"Coin",
										"CharacterHead",
										"Cauldron",
										"Book",
										"Ace",
										"King",
										"Queen",
										"Jack",
										"Ten",
										"WildOrb1",
										"WildOrb1",
										"WildOrb1"
									]
								},
								mask:{
									id:"reelMask",
									tgt:"reelsContainer",
									type:"Graphic",
									x:0,
									y:0,
									colour:"0xff00000",
									rect:{
										x:0,
										y:0,
										width:635,
										height:348
									}
								}
							}
						]
					},
					{
						type:"Sprite",
						x:121,
						y:10,
						imageName:"reelframe"
					},

					{
						type:"Sprite",
						imageName:"reellogo",
						x:252,
						y:32
					},
					{
						type:"WinlineContainer",
						id:"winlineContainer",
						x:190,
						y:170,
						width:640,
						height:348,
						symbolSize:{width:120, height:116},
						winlinePatterns:"",
						winlineSize:6,
						winlines:[
							"0xff0000",
							"0x0070bb",
							"0x002585",
							"0xffcfb9",
							"0xff62a8",
							"0xff8b00",
							"0xff137c",
							"0x00ff00",
							"0xfbd920",
							"0xff2b00",
							"0x60ffff",
							"0xffff00",
							"0x29abe1",
							"0xacff3e",
							"0x29abe1",
							"0xacacac",
							"0x00a060",
							"0xdb0000",
							"0x5258ff",
							"0x00d100",
							"0xd9df20"
						]
					},			
				]
			}
			
		]
	}

}